# Site settings
title: The résumé of Nicholas Harris
author:
  address:
      street: Moonmuang Road Lane 1
      town: Chiang Mai
      postcode: 50300
      country: Thailand
  email: info@practical-healing.com
  name: Nicholas
  title: Therapist and teacher
  phone: +61 910 674352
  website: http://www.practical-healing.com/
description: > # this means to ignore newlines until "baseurl:"
  Powered by Jekyll, and Github Pages ready, Jekyll-cv is a lightweight and lightning-fast
  html résumé making machine from @nternetinspired. Because web developers shouldn't
  showcase their skills on bits of dead tree.
baseurl: "/jekyll-resume/" # the subpath of your site, e.g. /blog/
url: "http://nternetinspired.github.io" # the base hostname & protocol for your site

# Compress html
compress_html:
  clippings: ['!--', html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

# Build settings
markdown: kramdown
sass:
    style: :compressed
